server:
  port: 8083 # Bidding Service runs on 8083

spring:
  application:
    name: bidding-service
  datasource:
    url: jdbc:h2:mem:bidtodb
    driverClassName: org.h2.Driver
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/