server:
  port: 8082 # Job Service runs on 8082

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:h2:mem:jobdb
    driverClassName: org.h2.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/